/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package in.ac.sbps.frame;

import in.ac.sbps.panel.StudentDetail;
import in.ac.sbps.panel.TeacherDetail;
import in.ac.sbps.panel.TeacherSearch;
import in.ac.sbps.util.SClass;

/**
 *
 * @author mahavir.singh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        studentMenu = new javax.swing.JMenu();
        addStudentMenuItem = new javax.swing.JMenuItem();
        editStudentMenuItem = new javax.swing.JMenuItem();
        deleteStudentMenuItem = new javax.swing.JMenuItem();
        teacherMenu = new javax.swing.JMenu();
        addTeacherMenuItem = new javax.swing.JMenuItem();
        editTeacherMenuItem = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        studentSearchMenuItem = new javax.swing.JMenuItem();
        teacherSearchMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        welcomeLabel.setText("Welcome to SBPS");

        studentMenu.setText("Student");

        addStudentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        addStudentMenuItem.setText("Add");
        addStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentMenuItemActionPerformed(evt);
            }
        });
        studentMenu.add(addStudentMenuItem);

        editStudentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        editStudentMenuItem.setText("Edit");
        editStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentMenuItemActionPerformed(evt);
            }
        });
        studentMenu.add(editStudentMenuItem);

        deleteStudentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteStudentMenuItem.setText("Delete");
        deleteStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentMenuItemActionPerformed(evt);
            }
        });
        studentMenu.add(deleteStudentMenuItem);

        jMenuBar1.add(studentMenu);

        teacherMenu.setText("Teacher");

        addTeacherMenuItem.setText("Add");
        addTeacherMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherMenuItemActionPerformed(evt);
            }
        });
        teacherMenu.add(addTeacherMenuItem);

        editTeacherMenuItem.setText("Edit");
        teacherMenu.add(editTeacherMenuItem);

        jMenuBar1.add(teacherMenu);

        searchMenu.setText("Search");

        studentSearchMenuItem.setText("Student");
        studentSearchMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchMenuItemActionPerformed(evt);
            }
        });
        searchMenu.add(studentSearchMenuItem);

        teacherSearchMenuItem.setText("Teacher");
        teacherSearchMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherSearchMenuItemActionPerformed(evt);
            }
        });
        searchMenu.add(teacherSearchMenuItem);

        jMenuBar1.add(searchMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(welcomeLabel)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentMenuItemActionPerformed
        StudentDetail studentDetail = new StudentDetail();
        this.setContentPane(studentDetail);
    }//GEN-LAST:event_addStudentMenuItemActionPerformed

    private void editStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentMenuItemActionPerformed
        StudentDetail studentDetail = new StudentDetail();
        this.setContentPane(studentDetail);
    }//GEN-LAST:event_editStudentMenuItemActionPerformed

    private void deleteStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentMenuItemActionPerformed
        StudentDetail studentDetail = new StudentDetail();
        this.setContentPane(studentDetail);
    }//GEN-LAST:event_deleteStudentMenuItemActionPerformed

    private void addTeacherMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherMenuItemActionPerformed
        TeacherDetail teacherDetail = new TeacherDetail();
        this.setContentPane(teacherDetail);
    }//GEN-LAST:event_addTeacherMenuItemActionPerformed

    private void studentSearchMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchMenuItemActionPerformed
        welcomeLabel.setText("");
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTable jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            StudentDataAdapter.getData(),
            new String [] {
                "Name", "Father Name", "Student Class", "Village"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, SClass.class, java.lang.String.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        pack();
    }//GEN-LAST:event_studentSearchMenuItemActionPerformed

    private void teacherSearchMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherSearchMenuItemActionPerformed
        TeacherSearch teacherSearch = new TeacherSearch();
        this.setContentPane(teacherSearch);
    }//GEN-LAST:event_teacherSearchMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addStudentMenuItem;
    private javax.swing.JMenuItem addTeacherMenuItem;
    private javax.swing.JMenuItem deleteStudentMenuItem;
    private javax.swing.JMenuItem editStudentMenuItem;
    private javax.swing.JMenuItem editTeacherMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu searchMenu;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JMenuItem studentSearchMenuItem;
    private javax.swing.JMenu teacherMenu;
    private javax.swing.JMenuItem teacherSearchMenuItem;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
